package seller

import (
	inflow "github.com/inflowpayai/inflow-go"
	"net/http"
	"testing"
	"time"

	"github.com/inflowpayai/inflow-go/mpp"
)

func TestNodeChallengeBinding(t *testing.T) {
	request, err := mpp.Encode(map[string]any{"amount": "1", "currency": "USDC", "recipient": "11111111-1111-4111-8111-111111111111", "methodDetails": map[string]any{"rail": "balance"}})
	if err != nil {
		t.Fatal(err)
	}
	expires := "2099-01-01T00:00:00Z"
	opaque := "eyJyb3V0ZSI6InBhaWQifQ"
	c := mpp.Challenge{ID: "1xeq8MPvFrnSLrt7iYLFhommRNLmjKC_eNKDWSRd-Q8", Realm: "seller.example", Method: "inflow", Intent: "charge", Request: request, Expires: &expires, Opaque: &opaque}
	// Generated by the actual mppx 0.8.17 Challenge.from implementation.
	if got := challengeID(c, "test-only-key"); got != c.ID {
		t.Fatal(got)
	}
	route := Route{Realm: c.Realm, SecretKey: "test-only-key", Opaque: &opaque}
	offer := PreparedOffer{Method: c.Method, Intent: c.Intent, Request: request}
	credential := mpp.Credential{Challenge: c, Payload: map[string]any{}}
	if !matches(route, offer, credential) {
		t.Fatal("Node challenge rejected")
	}
	for _, mutate := range []func(*mpp.Challenge){
		func(c *mpp.Challenge) { c.ID = "forged" }, func(c *mpp.Challenge) { c.Expires = nil }, func(c *mpp.Challenge) { v := "bad"; c.Expires = &v }, func(c *mpp.Challenge) { v := "2000-01-01T00:00:00Z"; c.Expires = &v },
		func(c *mpp.Challenge) { c.Realm = "other" }, func(c *mpp.Challenge) { v := "different"; c.Opaque = &v }, func(c *mpp.Challenge) { c.Method = "tempo" }, func(c *mpp.Challenge) { c.Intent = "subscription" },
		func(c *mpp.Challenge) { c.Request = "bad"; c.ID = challengeID(*c, route.SecretKey) }, func(c *mpp.Challenge) { c.Request = "W10"; c.ID = challengeID(*c, route.SecretKey) },
		func(c *mpp.Challenge) { c.Request = "e30"; c.ID = challengeID(*c, route.SecretKey) },
	} {
		value := credential
		mutate(&value.Challenge)
		if matches(route, offer, value) {
			t.Fatal("tampered credential accepted")
		}
	}
	offer.Request = "bad"
	if matches(route, offer, credential) {
		t.Fatal("bad expected request accepted")
	}
	for _, header := range []string{"", "Bearer app", "Payment", "Payment invalid", "Payment a b"} {
		_, err := paymentCredential([]string{header})
		if header != "" && header != "Bearer app" && err == nil {
			t.Fatal(header)
		}
	}
	encoded, _ := mpp.EncodeCredential(credential)
	if _, err := paymentCredential([]string{"Payment " + encoded, "Payment " + encoded}); err == nil {
		t.Fatal("duplicate payment accepted")
	}
	if got, err := paymentCredential([]string{"Bearer app, Payment " + encoded}); err != nil || got == nil {
		t.Fatal(err)
	}
}

func TestRouteConfiguration(t *testing.T) {
	c, _ := New(inflow.Options{})
	next := http.HandlerFunc(func(http.ResponseWriter, *http.Request) {})
	for _, route := range []Route{{}, {Realm: "r", SecretKey: "k", Offers: []Offer{{}}, Lifetime: -time.Second}} {
		if _, err := c.Protect(route, next); err == nil {
			t.Fatal("accepted bad route")
		}
	}
	opaque := "original"
	if _, err := c.Protect(Route{Realm: "r", SecretKey: "k", Offers: []Offer{{Charge: &mpp.ChargeRequest{Amount: "1", Currency: "USDC"}}}, Opaque: &opaque}, next); err != nil {
		t.Fatal(err)
	}
}
